name: note_names
description: Note Names visualizer.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
