name: note_names
description: Note Names visualizer.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  music_notes:
    git:
      url: https://github.com/albertms10/music_notes.git

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
